### ISSUE TITLE
Tuned issues on RHEL6

### ISSUE THREAD

**Issue by williamkorb** [alexharv074/puppet-disable_transparent_hugepage#5]
I ran into some issues when trying to use your module on RHEL6:

1. We did not have tuned installed, so agent runs failed:

Error: Cannot create /etc/tuned/custom; parent directory /etc/tuned does not exist
Error: /Stage[main]/Disable_transparent_hugepage/File[/etc/tuned/custom]/ensure: change from absent to directory failed: Cannot create /etc/tuned/custom; parent directory /etc/tuned does not exist

2. I installed tuned, and that did not create /etc/tuned, so it still failed. I had to add a File["/etc/tuned"] resource to create it.

3. Performing those first two steps still resulted in a failure, this time because it expected to find /sbin/tuned-adm, but on RHEL6, it is /usr/bin/tuned-adm.

With all that said, if tuned is an optional package on RHEL6 (which it appears to be the case), I would prefer to not have your module assume that it is present, and instead, only do the tuned stuff if it is.

**Comment by alex-harvey-z3q** [comment]
Hi @williamkorb 

I agree with your analysis.

It has been quite a while since I worked on this module and/or used disable_transparent_hugepages. What is needed here is a custom fact in the module named "is_tuned_installed" that returns true or false based on the output of rpm -q tuned.

And in point 3, add a path to the Exec so that it tries to find tuned-adm in either /usr/bin or /sbin.

Would you be interested in doing the feature? If not, I'll see if I can figure this out when I have some spare time.

**Comment by williamkorb** [comment]
Alex,
    
    Thanks for your response. I'll see if I can free up some time and
    look into it. I've actually also found some issues with the MongoDB
    module that I installed, and I'm working on that one first because I
    have no acceptable work-around for that one, yet.
    
    Bill

**Comment by alex-harvey-z3q** [comment]
@williamkorb fyi I am going to implement this unless you're already working on it? Give me a couple of days.

**Comment by alex-harvey-z3q** [comment]
@williamkorb , having another look at this and re-reading the MongoDB notes https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

It looks like the tuned-adm command is required to disable transparent_hugepage which is the point of the module. So, doing nothing if tuned is not installed doesn't seem to be the right approach. 

Any other ideas?

**Comment by alex-harvey-z3q** [comment]
@williamkorb , I have released version 1.4.0 of this. Note that on closer inspection I found that the instructions at MongoDB had changed quite a bit since I wrote this module several years ago, see 
https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

All of the changes were tested using Beaker on CentOS 6 & 7. Let me know if you find any further issues?

If your requirement remains for this module to not install tuned then you would have to handle that in your roles & profiles.

Thank you for reporting this issue by the way.
